* TwitterServer
  :PROPERTIES:
  :CUSTOM_ID: twitterserver
  :END:

  =TwitterServer= defines a template from which servers at Twitter are
  built. It provides common application components such as an
  administrative HTTP server, tracing, stats, etc. These features are
  wired in correctly for use in production at Twitter.

** Status
   :PROPERTIES:
   :CUSTOM_ID: status
   :END:

   This project is used in production at Twitter (and many other
   organizations), and is being actively developed and maintained.

** Documentation
   :PROPERTIES:
   :CUSTOM_ID: documentation
   :END:

   Browse the [[https://twitter.github.io/twitter-server/][user guide]].

** Getting involved
   :PROPERTIES:
   :CUSTOM_ID: getting-involved
   :END:

   -  Website: https://twitter.github.io/twitter-server/
   -  Source: https://github.com/twitter/twitter-server/
   -  Mailing List:
     [[https://groups.google.com/forum/#!forum/finaglers][finaglers@googlegroups.com]]

** Contributing
   :PROPERTIES:
   :CUSTOM_ID: contributing
   :END:

   We feel that a welcoming community is important and we ask that you
   follow Twitter's
   [[https://engineering.twitter.com/opensource/code-of-conduct][Open
   Source Code of Conduct]] in all interactions with the community.

   The =master= branch of this repository contains the latest stable
   release of TwitterServer, and weekly snapshots are published to the
   =develop= branch. In general pull requests should be submitted against
   =develop=. See
   [[https://github.com/twitter/twitter-server/blob/master/CONTRIBUTING.md][CONTRIBUTING.md]]
   for more details about how to contribute.
